export default  {
	USER_SIGN_UP: 'USER_SIGN_UP',
	USER_SIGN_IN: 'USER_SIGN_IN',
	USER_SIGN_OUT: 'USER_SIGN_OUT',
	START_LOAD: '_START_LOAD',
	FINISH_LOAD: '_FINISH_LOAD',
	GET_ERRORS: 'GET_ERRORS',
	GET_USER_INFO: 'GET_USER_INFO',
	GET_MARKER: 'GET_MARKER',
	SAVE_MARKERS: 'SAVE_MARKERS',

};